### ISSUE TITLE
Error selecting the mouse

### ISSUE THREAD

**Issue by DawfukFR** [konkitoman/autoclicker#12]
❯ sudo theclicker --clear-cache
Select input device:
 Mouses:
  3: Device:        R3 Gaming Mouse
 Keyboards:
  0: Device: ITE Tech. Inc. ITE Device(8295) Keyboard
  1: Device: ITE Tech. Inc. ITE Device(8176) Keyboard
  2: Device:        R3 Gaming Mouse Keyboard
-> ^[[6~
Is not an number!
Select input device:
 Mouses:
  3: Device:        R3 Gaming Mouse
 Keyboards:
  0: Device: ITE Tech. Inc. ITE Device(8295) Keyboard
  1: Device: ITE Tech. Inc. ITE Device(8176) Keyboard
  2: Device:        R3 Gaming Mouse Keyboard
-> 3
Device selected:        R3 Gaming Mouse, Is Ok [Y/n]
-> Y
Using:        R3 Gaming Mouse
Error: No such device (os error 19)
Not having access to create device, try as root!

**Comment by konkitoman** [comment]
What is the OS distribution that are you using?
Give me the output of this command
```bash
ls -al /dev/uinput
```
And
```bash
modprobe uinput
```
The modprobe output should be empty!

**Comment by DawfukFR** [comment]
Archlinux

crw-rw----+ 1 root root 10, 223  2 oct.  14:29 /dev/uinput

and sudo modprobe uinput is empty

**Comment by DawfukFR** [comment]
i have found that my old mouse work fine but not my new one
Is it because it is detected at the same time as keyboard?

**Comment by konkitoman** [comment]
From what i'm seeing, I means that the uinput module is not loaded!
If you run `sudo modprobe uinput` that should load the module, then everything should work

Source:
https://github.com/rmst/yoke/issues/9
