### ISSUE TITLE
[Suggestion] Add a hold mode

### ISSUE THREAD

**Issue by Spiderfffun** [konkitoman/autoclicker#13]
I usually don't use toggle with my autoclickers, and from looking at the code hold would be simple to add (but I don't have enough rust experience to do it well)

**Comment by konkitoman** [comment]
I added hold mode, in the latest commit [8c785d6](https://github.com/konkitoman/autoclicker/commit/8c785d6e9639beac91ee46ef2a822ef038efd3e9) 

I will make a new release after you @Spiderfffun close the issue.
