### ISSUE TITLE
Default yes/no choice not working

### ISSUE THREAD

**Issue by Rijaja** [konkitoman/autoclicker#9]
When presented with the `[Y/n]` choice, pressing return with an empty input will not select the default choice (yes).
Terminal output:
```
Select input device: 
 Mouses: 
  1: Device: Asus Keyboard
  3: Device: ASUS ROG SICA
 Keyboards: 
  0: Device: ASUF1205:00 2808:0106 Touchpad
  2: Device: ASUS ROG SICA Keyboard
-> 3  
Device selected: ASUS ROG SICA, Is Ok [Y/n]
-> 
Select input device: 
 Mouses: 
  1: Device: Asus Keyboard
  3: Device: ASUS ROG SICA
 Keyboards: 
  0: Device: ASUF1205:00 2808:0106 Touchpad
  2: Device: ASUS ROG SICA Keyboard
->
```

Source of the issue: [device.rs:276](https://github.com/konkitoman/autoclicker/blob/063ae7c942a9ee2f1f9684e387a850535eb65e31/src/device.rs#L276):
```rust
if user_input.trim() == "Y" || user_input.trim() == "y" {
```

Maybe the isn't a bug but just a misunderstanding on your part, and I don't blame you, it's kind of an unwritten rule. When a terminal shows a yes/no choice, or any kind of choice where the user enters a letter, a capital letter means it is the default choice, ie the one that will be selected if the user enters an empty input. So in your case, with `[Y/n]`, it means "press y or nothing to say yes, press n to say no".

If it is your intent for the default behavior to be "no", you should change `[Y/n]` to `[y/N]`. Otherwise you should change the condition.

**Comment by Rijaja** [comment]
maybe this seems like a very unimportant detail to some but I was genuinely confused why the program wouldn't work, I was stuck in a confirmation loop because it kept counting as a "no" while I thought it was counting as a "yes".

**Comment by konkitoman** [comment]
Thanks, I didn't know that!
